### ISSUE TITLE
Add Web Worker support

### ISSUE THREAD

**Issue by micahyoung** [docker/extensions-sdk#172]
## Summary

The client library is unusable within [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), which are useful for asynchronous I/O operations like fetching and processing external data and loading/running WASM modules or other libraries that may need to be isolated in a separate thread, allowing the main UI thread to remain responsive.

The cause appears to be that `window.ddClient` is required by the client library but only injected into the main UI thread, and not in Web Worker threads.

The fix would likely be to inject a `ddClient` into every Web Worker thread's environment, in addition to the main UI thread.

## Attempted Workarounds
* Transferring the `ddClient` object into the Web Worker with the `postMessage` [transfer](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage#parameters) param - fails with `not transferrable` error.

## Repro
1. Create new extension
    ```bash
    docker extension init MyExtension
    ```

1. Create a Web Worker that attempts to import and use client
    `MyExtension/ui/src/webWorker.js`
    ```
    import {createDockerDesktopClient} from '@docker/extension-api-client';
    
    const client = createDockerDesktopClient()
    ```

1. Append Worker initialization to `index.js`
    `MyExtension/ui/src/index.js`
    ```javascript
    ...
    import App from "./App";
    
    // eslint-disable-next-line import/no-webpack-loader-syntax
    import MyWorker from "worker-loader!./webWorker.js";
    
    const worker = new Worker(new MyWorker())
    
    ReactDOM.render(
    ...
    ```

1. Install extension with debug window
    ```
    make install-extension
    docker extension dev debug <myhubuser/myextension>
    ```

1. Navigate to extension in Docker Desktop and see error in Debug Console
    ```
    Uncaught ReferenceError: window is not defined
        at index.js:2:35
        at webWorker.js:3:16
        at webWorker.a94eac44.worker.js:1:257
    ```

**Comment by micahyoung** [comment]
I realize this will probably need to be fixed in Docker Desktop, not here in the SDK, but I wasn't sure where to file the issue where it would be most easily tracked.
